version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      python:
        applies-to: version-updates
        patterns: ["*"]
  - package-ecosystem: pip
    directory: /requirements/locks
    schedule:
      interval: weekly
    groups:
      python:
        applies-to: version-updates
        patterns: ["*"]
  - package-ecosystem: pip
    directory: /web
    schedule:
      interval: weekly
    groups:
      python:
        applies-to: version-updates
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        applies-to: version-updates
        patterns: ["*"]