"""Lock provenance: every hash lock names its canonical input and regeneration command.

The acceptance criteria behind these tests come from the supply-chain audit: no
generated dependency lock may exist without a canonical input manifest and a
reproducible regeneration command, and the same family of locks must agree
about package sets and pinned versions across platforms. The tests are
offline; they prove the recorded provenance is internally consistent, not that
a fresh pip-compile run reproduces each committed lock byte-for-byte (the
resolver moves as indexes change — the cross-platform regeneration procedure
is documented in requirements/README.md).
"""

from __future__ import annotations

import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REQUIREMENTS = ROOT / "requirements"
LOCKS = REQUIREMENTS / "locks"
PLATFORMS = ("linux", "macos", "windows")
REGENERATION_FLAGS = (
    "--allow-unsafe",
    "--generate-hashes",
    "--strip-extras",
)

# lock family -> canonical input file; every entry is the complete mapping.
FAMILY_INPUTS = {
    "base": "base.in",
    "runtime": "runtime.in",
    "release": "release.in",
    "quality": "quality.in",
    "audit": "audit.in",
}

# Marker-gated transitive packages each platform may add to the release lock
# and (for windows) the runtime lock. Everything else must be portable.
RELEASE_MARKER_PACKAGES = {
    "linux": frozenset(),
    "macos": frozenset({"macholib"}),
    "windows": frozenset({"colorama", "pefile", "pywin32", "pywin32-ctypes"}),
}
RUNTIME_MARKER_PACKAGES = {
    "linux": frozenset(),
    "macos": frozenset(),
    "windows": frozenset({"colorama", "pywin32"}),
}


def lock_paths(family: str) -> tuple[Path, ...]:
    """Return every committed lock generated by one canonical input."""
    if family == "quality":
        return (LOCKS / "quality-linux-x86_64.txt",)
    if family == "audit":
        return (LOCKS / "audit-python311.txt",)
    return tuple(LOCKS / f"{family}-{platform}-x86_64.txt" for platform in PLATFORMS)


def pinned_requirement(line: str) -> tuple[str, str] | None:
    """Parse one exact `name==version` pin from a lock or input body line."""
    match = re.match(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s\\]+)", line)
    return (match.group(1).lower(), match.group(2)) if match else None


def body_pins(path: Path) -> dict[str, str]:
    """Return the exact pins declared by a file, ignoring comment lines."""
    pins: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("#"):
            continue
        pin = pinned_requirement(line)
        if pin is not None:
            name, version = pin
            if name in pins and pins[name] != version:
                raise AssertionError(f"{path.name} pins {name} twice with different versions")
            pins[name] = version
    return pins


def assert_family_agrees(
    test: unittest.TestCase,
    family: str,
    marker_packages: dict[str, frozenset[str]] | None = None,
) -> None:
    """Compare complete package sets and versions across one family's locks.

    A platform lock may add only its documented marker packages; a surplus or
    missing package anywhere else, or any shared package pinned to different
    versions, fails. Comparing the complete sets (not just shared names) is
    what stops a platform from quietly accumulating extra dependencies.
    """
    with test.subTest(family=family):
        locks = lock_paths(family)
        reference = body_pins(locks[0])
        for index, lock in enumerate(locks[1:], start=1):
            pins = body_pins(lock)
            platform = PLATFORMS[index] if family in {"base", "runtime", "release"} else "linux"
            allowed = (marker_packages or {}).get(platform, frozenset())
            surplus = set(pins) - set(reference) - allowed
            test.assertFalse(
                surplus,
                f"{lock.name} added packages beyond the portable set and "
                f"documented markers: {sorted(surplus)}",
            )
            missing = set(reference) - set(pins)
            test.assertFalse(
                missing,
                f"{lock.name} lost portable packages: {sorted(missing)}",
            )
            differing = {
                name
                for name, version in pins.items()
                if name in reference and version != reference[name]
            }
            test.assertFalse(
                differing,
                f"{lock.name} disagrees with {locks[0].name} on {sorted(differing)}",
            )


class LockProvenanceTests(unittest.TestCase):
    def test_every_lock_family_has_a_canonical_input(self):
        for family, input_name in FAMILY_INPUTS.items():
            with self.subTest(family=family):
                for lock in lock_paths(family):
                    self.assertTrue(lock.is_file(), lock)
                self.assertTrue((REQUIREMENTS / input_name).is_file(), input_name)

    def test_every_lock_documents_its_input_and_regeneration_command(self):
        for family, input_name in FAMILY_INPUTS.items():
            for lock in lock_paths(family):
                with self.subTest(lock=lock.name):
                    text = lock.read_text(encoding="utf-8")
                    # pip-compile 7.6.1 writes this exact header line; keep the
                    # committed header identical to what regeneration produces.
                    command = (
                        f"pip-compile --allow-unsafe --generate-hashes "
                        f"--output-file=requirements/locks/{lock.name} "
                        f"--strip-extras requirements/{input_name}"
                    )
                    self.assertIn(command, text)
                    position = text.find(command)
                    header = text[:position]
                    self.assertIn("This file is autogenerated by pip-compile", header)

    def test_canonical_inputs_document_the_same_regeneration_command(self):
        for family, input_name in FAMILY_INPUTS.items():
            for lock in lock_paths(family):
                with self.subTest(input=input_name, lock=lock.name):
                    text = (REQUIREMENTS / input_name).read_text(encoding="utf-8")
                    command = (
                        f"python -m piptools compile --allow-unsafe --generate-hashes "
                        f"--output-file=requirements/locks/{lock.name} "
                        f"--strip-extras requirements/{input_name}"
                    )
                    self.assertIn(command, text)

    def test_regeneration_command_flags_are_all_present(self):
        for family in FAMILY_INPUTS:
            for lock in lock_paths(family):
                with self.subTest(lock=lock.name):
                    text = lock.read_text(encoding="utf-8")
                    for flag in REGENERATION_FLAGS:
                        self.assertIn(flag, text, f"{lock.name} is missing {flag}")

    def test_every_direct_input_pin_is_locked_identically_in_every_family_lock(self):
        for family, input_name in FAMILY_INPUTS.items():
            direct_pins = body_pins(REQUIREMENTS / input_name)
            self.assertTrue(direct_pins, input_name)
            for lock in lock_paths(family):
                with self.subTest(lock=lock.name):
                    locked = body_pins(lock)
                    for name, version in direct_pins.items():
                        self.assertEqual(
                            locked.get(name),
                            version,
                            f"{lock.name} must lock {name}=={version} from {input_name}",
                        )

    def test_no_lock_carries_extras_qualified_pins(self):
        """--strip-extras is canonical: an extras pin means a stale or hand-edited lock."""
        for family in FAMILY_INPUTS:
            for lock in lock_paths(family):
                with self.subTest(lock=lock.name):
                    for line in lock.read_text(encoding="utf-8").splitlines():
                        if line.startswith("#"):
                            continue
                        self.assertNotRegex(
                            line,
                            r"^[A-Za-z0-9][A-Za-z0-9._-]*\[[^]]+\]==",
                            f"{lock.name} still carries an extras-qualified pin; "
                            f"regenerate with --strip-extras",
                        )

    def test_base_locks_are_identical_across_platforms(self):
        """The bootstrap environment is fully portable: no platform may add anything."""
        assert_family_agrees(self, "base")

    def test_runtime_locks_differ_only_by_documented_windows_markers(self):
        assert_family_agrees(self, "runtime", RUNTIME_MARKER_PACKAGES)

    def test_release_locks_differ_only_by_environment_marker_packages(self):
        assert_family_agrees(self, "release", RELEASE_MARKER_PACKAGES)

    def test_single_platform_families_exist(self):
        for family in ("quality", "audit"):
            with self.subTest(family=family):
                self.assertEqual(len(lock_paths(family)), 1)


if __name__ == "__main__":
    unittest.main()
