"""Lock provenance: every hash lock names its canonical input and regeneration command.

The acceptance criteria behind these tests come from the supply-chain audit: no
generated dependency lock may exist without a canonical input manifest and a
reproducible regeneration command, and the same family of locks must agree
about every pinned version across platforms. The tests are offline; they prove
the recorded provenance is internally consistent, not that a fresh pip-compile
run reproduces each committed lock byte-for-byte (the resolver moves as indexes
change — the cross-platform regeneration procedure is documented in
requirements/README.md).
"""

from __future__ import annotations

import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REQUIREMENTS = ROOT / "requirements"
LOCKS = REQUIREMENTS / "locks"
PLATFORMS = ("linux", "macos", "windows")
REGENERATION_FLAG_ORDER = (
    "--allow-unsafe",
    "--generate-hashes",
    "--strip-extras",
)

# lock family -> canonical input file; every entry is the complete mapping.
FAMILY_INPUTS = {
    "base": "base.in",
    "runtime": "runtime.in",
    "release": "release.in",
    "quality": "quality.in",
    "audit": "audit.in",
}


def lock_paths(family: str) -> tuple[Path, ...]:
    """Return every committed lock generated by one canonical input."""
    if family == "quality":
        return (LOCKS / "quality-linux-x86_64.txt",)
    if family == "audit":
        return (LOCKS / "audit-python311.txt",)
    return tuple(LOCKS / f"{family}-{platform}-x86_64.txt" for platform in PLATFORMS)


def pinned_requirement(line: str) -> tuple[str, str] | None:
    """Parse one exact `name==version` pin from a lock or input body line."""
    match = re.match(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s\\]+)", line)
    return (match.group(1).lower(), match.group(2)) if match else None


def body_pins(path: Path) -> dict[str, str]:
    """Return the exact pins declared by a file, ignoring comment lines."""
    pins: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("#"):
            continue
        pin = pinned_requirement(line)
        if pin is not None:
            name, version = pin
            if name in pins and pins[name] != version:
                raise AssertionError(f"{path.name} pins {name} twice with different versions")
            pins[name] = version
    return pins


class LockProvenanceTests(unittest.TestCase):
    def test_every_lock_family_has_a_canonical_input(self):
        for family, input_name in FAMILY_INPUTS.items():
            with self.subTest(family=family):
                for lock in lock_paths(family):
                    self.assertTrue(lock.is_file(), lock)
                self.assertTrue((REQUIREMENTS / input_name).is_file(), input_name)

    def test_every_lock_documents_its_input_and_regeneration_command(self):
        for family, input_name in FAMILY_INPUTS.items():
            for lock in lock_paths(family):
                with self.subTest(lock=lock.name):
                    text = lock.read_text(encoding="utf-8")
                    command = (
                        f"pip-compile --allow-unsafe --generate-hashes --strip-extras "
                        f"--output-file=requirements/locks/{lock.name} requirements/{input_name}"
                    )
                    self.assertIn(command, text)
                    position = text.find(command)
                    header = text[:position]
                    self.assertIn("This file is autogenerated by pip-compile", header)

    def test_canonical_inputs_document_the_same_regeneration_command(self):
        for family, input_name in FAMILY_INPUTS.items():
            for lock in lock_paths(family):
                with self.subTest(input=input_name, lock=lock.name):
                    text = (REQUIREMENTS / input_name).read_text(encoding="utf-8")
                    command = (
                        f"python -m piptools compile --allow-unsafe --generate-hashes "
                        f"--strip-extras "
                        f"--output-file=requirements/locks/{lock.name} requirements/{input_name}"
                    )
                    self.assertIn(command, text)

    def test_regeneration_command_keeps_flag_order_stable(self):
        """A reordered flag set would make documented commands diverge from pip-compile headers."""
        flags = list(REGENERATION_FLAG_ORDER)
        for family in FAMILY_INPUTS:
            for lock in lock_paths(family):
                with self.subTest(lock=lock.name):
                    text = lock.read_text(encoding="utf-8")
                    positions = [text.find(flag) for flag in flags]
                    self.assertTrue(
                        all(position >= 0 for position in positions),
                        f"{lock.name} is missing a regeneration flag",
                    )
                    self.assertEqual(positions, sorted(positions), f"{lock.name} reorders flags")

    def test_every_direct_input_pin_is_locked_identically_in_every_family_lock(self):
        for family, input_name in FAMILY_INPUTS.items():
            direct_pins = body_pins(REQUIREMENTS / input_name)
            self.assertTrue(direct_pins, input_name)
            for lock in lock_paths(family):
                with self.subTest(lock=lock.name):
                    locked = body_pins(lock)
                    for name, version in direct_pins.items():
                        self.assertEqual(
                            locked.get(name),
                            version,
                            f"{lock.name} must lock {name}=={version} from {input_name}",
                        )

    def test_portable_families_agree_on_versions_across_platforms(self):
        """base and runtime environments are portable: their locks must not drift apart."""
        for family in ("base", "runtime", "quality", "audit"):
            with self.subTest(family=family):
                reference: dict[str, str] | None = None
                reference_name = ""
                for lock in lock_paths(family):
                    pins = body_pins(lock)
                    if reference is None:
                        reference, reference_name = pins, lock.name
                        continue
                    differing = {
                        name for name in reference if name in pins and pins[name] != reference[name]
                    }
                    self.assertFalse(
                        differing,
                        f"{lock.name} disagrees with {reference_name} on {sorted(differing)}",
                    )

    def test_release_locks_differ_only_by_environment_marker_packages(self):
        """Platform-specific transitive packages must stay on their own platform only."""
        marker_packages = {
            "linux": set(),
            "macos": {"macholib"},
            "windows": {"colorama", "pefile", "pywin32", "pywin32-ctypes"},
        }
        pins = {lock.name: body_pins(lock) for lock in lock_paths("release")}
        by_platform = {platform: pins[f"release-{platform}-x86_64.txt"] for platform in PLATFORMS}
        for platform, expected_only in marker_packages.items():
            own = set(by_platform[platform])
            for other, other_pins in by_platform.items():
                if other == platform:
                    continue
                leaked = own - set(other_pins) - expected_only
                self.assertFalse(
                    leaked,
                    f"{platform} lock gained packages that are neither portable "
                    f"nor documented as {platform}-only: {sorted(leaked)}",
                )


if __name__ == "__main__":
    unittest.main()
