import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from comic_sol_product import __version__


ROOT = Path(__file__).resolve().parents[1]

from scripts import sync_plugin_bundle  # noqa: E402


class PluginBundleTests(unittest.TestCase):
    def test_plugin_version_matches_package_version(self):
        metadata = json.loads((ROOT / ".codex-plugin/plugin.json").read_text(encoding="utf-8"))
        self.assertEqual(__version__, metadata["version"])

    def test_generated_plugin_bundle_matches_canonical_root(self):
        result = subprocess.run(
            [sys.executable, str(ROOT / "scripts/sync_plugin_bundle.py"), "--check"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
        )

        self.assertEqual(0, result.returncode, result.stdout + result.stderr)

    def test_check_detects_a_deleted_bundled_script(self):
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            bundle = root / "skills/comic-sol"
            source = root / "scripts/comic_sol.py"
            source.parent.mkdir(parents=True)
            source.write_text("canonical\n", encoding="utf-8")

            with (
                patch.object(sync_plugin_bundle, "ROOT", root),
                patch.object(sync_plugin_bundle, "BUNDLE", bundle),
            ):
                self.assertIn(Path("scripts/comic_sol.py"), sync_plugin_bundle.check())

    def test_generated_bytecode_is_not_treated_as_bundle_drift(self):
        with tempfile.TemporaryDirectory() as raw:
            bundle = Path(raw) / "skills/comic-sol"
            bundle.mkdir(parents=True)
            (bundle / "SKILL.md").write_text("skill\n", encoding="utf-8")
            cache = bundle / "scripts/__pycache__/comic_sol.cpython-311.pyc"
            cache.parent.mkdir(parents=True)
            cache.write_bytes(b"generated bytecode")

            with patch.object(sync_plugin_bundle, "BUNDLE", bundle):
                self.assertEqual({Path("SKILL.md")}, sync_plugin_bundle.actual_bundle_paths())

    def test_check_detects_deleted_canonical_and_orphaned_bundle_references(self):
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            bundle = root / "skills/comic-sol"
            references = bundle / "references"
            references.mkdir(parents=True)
            (references / "workflow.md").write_text("stale\n", encoding="utf-8")
            (references / "orphan.md").write_text("orphan\n", encoding="utf-8")

            with (
                patch.object(sync_plugin_bundle, "ROOT", root),
                patch.object(sync_plugin_bundle, "BUNDLE", bundle),
            ):
                drift = sync_plugin_bundle.check()

            self.assertIn(Path("references/workflow.md"), drift)
            self.assertIn(Path("references/orphan.md"), drift)


if __name__ == "__main__":
    unittest.main()
